syntax = "proto3";
import "common.proto";

package worker_api.v1;

service WorkerApi {
  rpc OpenClientConnection(stream ClientEvent) returns (stream ClientEvent);
  rpc OpenWorkerConnection(stream WorkerEvent) returns (stream WorkerEvent);
}

message Connect {
  string id = 1;
  common.v1.Addr addr = 2;
}

message ConnectResponse {
  string id = 1;
}

message Record {
  uint64 key = 1;
  bytes value = 2;
}

message SyncBatchRequest {
  string id = 1;
  repeated Record records = 2;
}

message SyncBatchResponse {
  string id = 1;
}

message WorkerEvent {
  oneof payload {
    Connect connect = 1;
    ConnectResponse connect_response = 2;
    SyncBatchRequest sync_batch_request = 3;
    SyncBatchResponse sync_batch_response = 4;
  }
}

enum RequestType {
  Get = 0;
  Put = 1;
  Delete = 2;
}

message Request {
  RequestType request_type = 1;
  uint64 key = 2;
  optional bytes value = 3;
  optional uint64 ttl = 4;
}

message Response {
  RequestType request_type = 1;
  uint64 key = 2;
  optional bytes value = 3;
}

message ClientEvent {
  oneof payload {
    Request request = 1;
    Response response = 2;
  }
}
